### PR TITLE
adding jotl cards and data to db

### PR DESCRIPTION
**Pull request by solomojb**
Hello,

 I have made more changes to the code base. This time allowing the database to have Jaws of the Lion functionality.  

 In this change set, i made it when future expansions come out (like frosthaven) it should be easier to add the data without changing the code too much. 

Jim

### CODE REVIEW

**Comment by solomojb** [comment]
Also snuck in a fix for issue #5.

**Comment by solomojb** [comment]
Also,  is it ok that i advertise the changes i am making on forums/reddit?  I just want to make sure people are aware of the work... ;)

**Comment by heisch** [comment]
> Also, is it ok that i advertise the changes i am making on forums/reddit? I just want to make sure people are aware of the work... ;)

Absolutely, at this point this is more your work than mine 😅 
I've also sent you an invite to have direct access to this repository a while ago (when you did your last PR, maybe check your spam?)

**Comment by solomojb** [comment]
Hmm. I don’t see it.

Does this mean I can commit directly to master? Would you still want to review the changes? How do I publish it?

Sorry for all the questions.  :)

Sent from my iPhone

On Sep 2, 2020, at 4:17 AM, Nicola Heisch <notifications@github.com> wrote:

﻿

Also, is it ok that i advertise the changes i am making on forums/reddit? I just want to make sure people are aware of the work... ;)

Absolutely, at this point this is more your work than mine 😅
I've also sent you an invite to have direct access to this repository a while ago (when you did your last PR, maybe check your spam?)

**Comment by heisch** [comment]
> Hmm. I don’t see it. Does this mean I can commit directly to master? Would you still want to review the changes? How do I publish it? Sorry for all the questions. :)

resent the collaboration invitation. It would mean you have direct access to the original repository and could push directly to master and also publish to github pages (https://heisch.github.io/gloomhaven-item-db/)

**Comment by solomojb** [comment]
Ok found the invitation it went to a different email.

Should i just merge my PR, or do you want a chance to review it? (I'd prefer the later if you have the time, but it's ok if you don't)

**Comment by heisch** [comment]
I'll gladly review the changes, but I probably won't have time this week

**Comment by solomojb** [comment]
No worries.  I would rather someone check the changes than me just blindly checking it in. :)

At your leisure. And thanks!

Sent from my iPhone

On Sep 2, 2020, at 1:39 PM, Nicola Heisch <notifications@github.com> wrote:

﻿

I'll gladly review the changes, but I probably won't have time this week

**Comment by solomojb** [comment]
Closing this as i found bugs... and want to rethink the way some things work.

**Pull request closed without merging**
