### PR TITLE
Add FC cards and Multi Slot Selection

### PR DESCRIPTION
**Pull request by solomojb**
Hello, another PR for you this time: This time it's smaller. 

Features of this PR:
Added Forgotten Circle Cards, Diviner to Solo Class list

Multi Select Slots:
A friend and i were playing around and thought it would be cool to have the ability to filter on multiple slots at once.

(If you prefer i do one feature per PR in the future let me know)

After this, i have one more (semi big) PR to post.

### CODE REVIEW

**Comment by heisch** [comment]
The new multi-slots filter doesn't work when displaying all items (Respect spoiler settings -> disabled)

**Comment by solomojb** [comment]
Just checked the website looks like it might have broken with that last push. Probably with the way I did the filtering.  I’ll take a look and fix it.

Sent from my iPhone

On Jul 30, 2020, at 4:41 AM, Nicola Heisch <notifications@github.com> wrote:

﻿

The new multi-slots filter doesn't work when displaying all items (Respect spoiler settings -> disabled)

**Comment by solomojb** [comment]
Fixed and pushed the bug fix ... was one line fix in useItems hook

**Comment by heisch** [comment]
Merged and deployed

**Pull request merged**
